### ISSUE TITLE
RabbitMQ - Alert if node is the only cluster member

### ISSUE THREAD

**Issue by cfarquhar** [rcbops/rpc-maas#102]
In a recent post-deployment QC review, it was identified that we may not receive an alert if a RabbitMQ node was the only node in the cluster.  Please check with @jrcloud or @toxick if more details are necessary.

**Comment by mancdaz** [comment]
Hi @cfarquhar @jrcloud @toxick

I'm closing this issue through lack of information. Please re-open if this continues to be a problem.
