### ISSUE TITLE
ansible-rpc-lxc v9.0.3 — `python-neutronclient` upgrades to known broken version

### ISSUE THREAD

**Issue by jpmontez** [rcbops/rpc-maas#126]
Within the `ansible-lxc-rpc` repo, `v9.0.3` branch, the specified version of `python-neutronclient` to install is set to `2.3.6`. 

However, within the `rpc-maas` repo, the [requirements.txt](https://github.com/rcbops/rpc-maas/blob/9.0.3/requirements.txt) file overrides this setting by specifying another version (`2.3.9`). This introduces a Keystone patch that ignores specified endpoint types (a known bug that's been patched in newer branches: https://bugs.launchpad.net/python-neutronclient/+bug/1368676). For our labs, this breaks client functionality due to our networking setup.

If the specific versions are removed from the `requirements.txt` file, then the packages can fallback to what's set in the developer's managed repositories.

**Comment by claco** [comment]
Closing as I believe this is fixed in 9.0.5+
