### ISSUE TITLE
Rewrite swift-recon.py to use python-swiftclient

### ISSUE THREAD

**Issue by sigmavirus24** [rcbops/rpc-maas#130]
All of the other checks similar to swift-recon.py use their client libraries so this should as well. That said, the swift team is moving away from actively developing python-swiftclient so we should also consider the viability of using python-openstacksdk. This will require the check registration to be rewritten in the playbooks.

**Comment by git-harry** [comment]
This repo is no longer actively maintained. If this issue is still valid please open a new issue at https://github.com/rcbops/rpc-openstack/issues
