### ISSUE TITLE
rabbitmq_status.py assumes cluster size of 3 hosts

### ISSUE THREAD

**Issue by BjoernT** [rcbops/rpc-maas#137]
The rabbitmq_status.py assumes cluster size of 3 hosts which is a hard coded number. In cases where we rabbitmq cluster > 3 nodes we will run into monitoring issues. Please either determine that from the cluster status or make a option available

**Comment by git-harry** [comment]
This repo is no longer actively maintained. If this issue is still valid please open a new issue at https://github.com/rcbops/rpc-openstack/issues
