### ISSUE TITLE
Add RabbitMQ monitor to alert when count(channel) > count(connection)

### ISSUE THREAD

**Issue by cfarquhar** [rcbops/rpc-maas#138]
Having any RabbitMQ connection servicing more than a single channel indicates a problem with agent <-> RabbitMQ communication.  We need an alert any time this occurs.

Expected behavior:
```
# rabbitmqctl list_connections channels | sort -n | tail -n1 
1
```

Indicates a problem:
```
# rabbitmqctl list_connections channels | sort -n | tail -n1 
186833
```

**Comment by sigmavirus24** [comment]
Closed by #139
