### ISSUE TITLE
Add SSL Cert Expiration Check/Alarm

### ISSUE THREAD

**Issue by claco** [rcbops/rpc-maas#140]
If the external api checks are monitoring https endpoints [instead of http], we should add a check/alarm to for the ssl certificate expiration date. This will help ensure that alarms are raised when the cert is nearing its expiration date [or has expired] so the cert gets updated before it impacts functionality.

This will be important going forward once we force https for all public/admin endpoints.

**Comment by mancdaz** [comment]
Remote checks are set up in the ansible playbooks, so moving this to launchpad:

https://bugs.launchpad.net/openstack-ansible/+bug/1408335
