### ISSUE TITLE
Create Disk Space Monitor Plugin

### ISSUE THREAD

**Issue by seancarlisle** [rcbops/rpc-maas#143]
Currently we do not have monitoring for disk space.  We have come across a couple of customers who had full /boot partitions due to apt's unattended upgrades installing new kernels and filling /boot (being addressed here: https://bugs.launchpad.net/openstack-ansible/+bug/1411897.)  We need a plugin in place to check the amount of free disk space on a host that will be used by our monitoring to proactively alert when a disk approaches certain thresholds.

Desired features:

-Checks all mounted filesystems.
-Accepts list of filesystems to exclude from check.
-Prints the name and percentage of disk space remaining for each mountpoint (is this do-able with maas_common?  Also, do the maas alerts support dicts or key-value pairs?)

**Comment by b3rnard0** [comment]
This is obsoleted as we are covering the work here: https://bugs.launchpad.net/openstack-ansible/+bug/1414249
