### ISSUE TITLE
queries_per_second is actually just cumulative queries

### ISSUE THREAD

**Issue by mancdaz** [rcbops/rpc-maas#151]
when the plugin queries mysql, total queries is returned but we report it as queries per second

https://github.com/rcbops/rpc-maas/blob/master/galera_check.py#L47

```
MariaDB [(none)]> show status where variable_name REGEXP '^Queries';
+---------------+--------+
| Variable_name | Value  |
+---------------+--------+
| Queries       | 376807 |
+---------------+--------+
```

We need some logic in the plugin to make 2 calls n seconds apart, and the delta is the qps

**Comment by git-harry** [comment]
This repo is no longer actively maintained. If this issue is still valid please open a new issue at https://github.com/rcbops/rpc-openstack/issues
