### ISSUE TITLE
Multiple openstack checks do not take a DNS name as argument

### ISSUE THREAD

**Issue by BjoernT** [rcbops/rpc-maas#157]
usage: nova_service_check.py [-h] [--host HOST] ip
nova_service_check.py: error: argument ip: invalid IPv4Address value: 'privapi.example.com'

That needs to be fixed

**Comment by BjoernT** [comment]
Affected is also neutron_service_check.py

**Comment by stevelle** [comment]
any fix for this probably needs a backport to juno
