### ISSUE TITLE
Monitor connections

### ISSUE THREAD

**Issue by cemason** [rcbops/rpc-maas#163]
Would it be possible to add a monitor to compare /proc/sys/net/ipv4/netfilter/ip_conntrack_max with /proc/sys/net/ipv4/netfilter/ip_conntrack_count and alert if the connections vs max connections is 90% or more?

**Comment by mancdaz** [comment]
@cemason I've added this to our backlog, so it can be prioritised and targeted for a future sprint.

**Comment by cemason** [comment]
Thanks!



—

**Comment by cfarquhar** [comment]
Thanks @mancdaz and @cemason.  Please expose both metrics to MaaS so we can get them in to graphana once it's available.

**Comment by cfarquhar** [comment]
Hi @mancdaz, We had another customer's environment fall over due to connections exceeding the conntrack max.  Can you please provide an update on when this will be implemented?

**Comment by sigmavirus24** [comment]
@mancdaz is out of office sick, but I'll ping @b3rnard0 to get this bumped regarding priority.

**Comment by b3rnard0** [comment]
@cfarquhar We are going to expedite this as part of our next sprint that starts on 4/2. We hope to have a fix some time in the early part of the sprint. I'll add an estimate closer to the 4/2 date.

@claco @mancdaz @sigmavirus24

**Comment by b3rnard0** [comment]
Fixed.
