### ISSUE TITLE
disk_utilisation.py has no executable bit set

### ISSUE THREAD

**Issue by BjoernT** [rcbops/rpc-maas#166]
The disk_utilisation.py usually fails because of the missing x bit.
Please add the mode to the repository so we don't have to set it always manually

**Comment by sigmavirus24** [comment]
Should this be backported to icehouse and juno?

**Comment by BjoernT** [comment]
Juno yes, icehouse no

**Comment by sigmavirus24** [comment]
@BjoernT see #169

**Comment by claco** [comment]
Appears to be fixed and backported. Closing issue.
