### ISSUE TITLE
Galera Check not working if wsrep_local_state is != 4 

### ISSUE THREAD

**Issue by BjoernT** [rcbops/rpc-maas#174]
In my case the check did not work properly if galera is in the following state:

wsrep_local_state	2
wsrep_local_state_comment	Donor/Desynced

wsrep_cluster_size	3
wsrep_cluster_status	Primary

wsrep_local_state_uuid	a1a1ed88-7582-11e4-a4dd-5be7e191d8a4
wsrep_cluster_state_uuid	a1a1ed88-7582-11e4-a4dd-5be7e191d8a4

the check did not return any out, neither a state or metrics

**Comment by git-harry** [comment]
This repo is no longer actively maintained. If this issue is still valid please open a new issue at https://github.com/rcbops/rpc-openstack/issues
