### ISSUE TITLE
Create memcache check

### ISSUE THREAD

**Issue by BjoernT** [rcbops/rpc-maas#176]
Currently we do not check important memcache metric like:
* bytes
* evictions
* curr_connections

Since memcache can affect the performance of openstack negatively we should have those checks in place

**Comment by mancdaz** [comment]
Hi @BjoernT 

Currently the memcached plugin has no actual alarms triggered on any of the metrics it collects.  Would you anticipate needing alarms for these additional metrics, or simply to gather the data to see performance over time?

**Comment by BjoernT** [comment]
@mancdaz The goal is to have alarm from my side, metrics collection is a side product for me. I'm particular interested in curr_connections that this metric does not hit the max connection limit and evictions. Ideally we won't have any evictions. Every evictions is indicating memory issues that objects don't survive the TTL.

**Comment by stevelle** [comment]
as I was just looking at OSAD's memcached I wanted to ensure we had maas metrics on memcached.

We have all the the metrics made available to maas here:
https://github.com/rcbops/rpc-openstack/blob/master/maas/memcached_status.py

that includes all of the named metrics in this card. What precisely do we need for alarms?

**Comment by git-harry** [comment]
This repo is no longer actively maintained. If this issue is still valid please open a new issue at https://github.com/rcbops/rpc-openstack/issues
