### ISSUE TITLE
disk_utilisation.py is not excluding nb block devices and bails out on 30 metric limit

### ISSUE THREAD

**Issue by BjoernT** [rcbops/rpc-maas#177]
disk_utilisation.py is not excluding nb block devices and bails out on 30 metric limit:
error Maximum of 30 metrics per checkerror Maximum of 30 metrics per check

I will create a pull request to remove those devices from the metric array

**Comment by nrb** [comment]
This is in master/kilo, needs to be pulled into juno.

**Comment by git-harry** [comment]
This repo is no longer actively maintained. If this issue is still valid please open a new issue at https://github.com/rcbops/rpc-openstack/issues
