### ISSUE TITLE
No alert for down compute node

### ISSUE THREAD

**Issue by paul5801** [rcbops/rpc-maas#186]
Currently in CDC environments we are not notified if a compute node goes hard down. nova_service_check.py only checks the service locally on itself.  This check needs to be performed from neighboring compute nodes and/or infra nodes to check if other nodes are up.  This has already happened to a customer where they had a compute node down for 8hrs and we never alerted on it.

**Comment by claco** [comment]
Can you define "compute node goes hard down"? Was the host machine completely dead, etc?

**Comment by paul5801** [comment]
In this specific case, the compute node had a RAID card failure and kernel panic'd and subsequently when they replaced the card during a maintenance we also did not get an alert.

**Comment by mancdaz** [comment]
We need to follow up with the maas team and find out why alerts are not raised when an agent stops checking in.

**Comment by claco** [comment]
I don't think that's ever been the case. If I stop the agent on my own servers, I don't get any notification. Did it used to work like that?

**Comment by mattt416** [comment]
Not as far as I'm aware.

**Comment by claco** [comment]
Hrm. In this case, I would think maybe the compute being down would mean there's something in `nova service-list` that we could monitor.

**Comment by mancdaz** [comment]
What if all compute nodes go down?

**Comment by mancdaz** [comment]
We should actually get something from this plugin. It checks administrative
state versus actual state of nova services

https://github.com/rcbops/rpc-maas/blob/master/nova_service_check.py

**Comment by cfarquhar** [comment]
nova_service_check.py does check service state, but it only does so from the local host that it's checking.  So, the monitor is in the same failure domain as the service it's monitoring.

https://github.com/rcbops/rpc-extras/blob/master/playbooks/roles/rpc_maas/tasks/local.yml#L242

@claco @mancdaz

**Comment by mancdaz** [comment]
Right, but the other compute nodes also poll their nova-api for nova services, which includes all compute nodes that are registered. If one is administratively up, but shows as down, we should be getting an alert.

**Comment by claco** [comment]
So, I was digging w/ @cloudnull.  The check on the computes pass --host (itself), so they only would error if they themselves go offline.

If you don't pass --host, it does return all metrics for all services...but currently, we're not dropping in that type of no-host check anywhere.

**Comment by claco** [comment]
@mancdaz @mattt416 While not ideal, in the interim, we could add an aggregate 1/0 flag so when something in nova service-list goes down, we can at least drop in a check/alert for it.

I'm not sure about adding the check/alarms to all the infras via ansible, as we might not want to keep them. At the very least, we should be able to manually configure some checks when the changed file is in place.

**Comment by mancdaz** [comment]
This is being taken care of by the 'agent down' alerting being rolled out currently by maas themselves, and as such is not something we need to track in this repo
