### ISSUE TITLE
rabbitmq_status.py issues

### ISSUE THREAD

**Issue by mattt416** [rcbops/rpc-maas#188]
I've started to see this type of failure on newly built clusters:

```
root@jenk-heat-158-node1:/usr/lib/rackspace-monitoring-agent/plugins# ./rabbitmq_status.py -H 172.29.236.126 -n jenk-heat-158-node1_rabbit_mq_container-fd99ca31
status error Detected RabbitMQ connections with multiple channels. Please check RabbitMQ and all Openstack consumers
root@jenk-heat-158-node1:/usr/lib/rackspace-monitoring-agent/plugins#
```

It looks like https://github.com/rcbops/rpc-maas/pull/139 introduced this change -- however the issue seems to involve us alarming when `channel['number'] > 1`, but `number` here is actually the channel number which doesn't make sense to alarm on (assuming I'm reading this correctly).

I believe what @cfarquhar requested was not implemented -- we should be checking /api/connections and not /api/channels, and perhaps we can alarm if channels > channel_max?  Some research will need to be done here as I'm not overly clear on the specifics of rabbitmq channels.

Mentioning @BjoernT for input.

--Matt

**Comment by mattt416** [comment]
Additionally, it would probably make more sense to write a metric for whatever we are testing here and then alarm against that, rather than just bail the plugin if some value is too high.  The problem w/ doing the latter is that we end up getting alerts for this that say rabbitmq_disk_free_alarm_status which is a bit misleading if you don't dig into the details of the alert.

**Comment by BjoernT** [comment]
After all the rule should be still, one connection has one channel. There is a blueprint for openstack to reuse connection while opening multiple channels. I do not know to which  RPC/openstack version this issue is related to, which might explain the change in behavior

**Comment by b3rnard0** [comment]
@mattt416 Please look into this though it's still a low priority issue.

**Comment by mattt416** [comment]
This is still not solved -- it doesn't fail constantly now but I do still get periodic errors on a relatively unused cluster.

**Comment by nrb** [comment]
Can this be closed? It appears to be merged in kilo and juno.

**Comment by nrb** [comment]
Actually I'm just going to close it, and if it shouldn't be, please re-open.
