### ISSUE TITLE
Missing rabbitmq metric

### ISSUE THREAD

**Issue by xeregin** [rcbops/rpc-maas#214]
rabbitmq_status.py (10.1.9) does not provide the 'rabbitmq_max_channels_per_conn--<container>' metric, which causes the MaaS checks (installed from os-ansible-deployment/rpc_deployment/playbooks/monitoring/) to alert.
As a sample, here is the output from a recent call to this script:
```
status okay
metric rabbitmq_uptime int64 529309065 ms
metric rabbitmq_messages int64 6780 messages
metric rabbitmq_ack int64 1375088 messages
metric rabbitmq_deliver_get int64 1375088 messages
metric rabbitmq_deliver int64 1375088 messages
metric rabbitmq_sockets_total int64 3594 fd
metric rabbitmq_publish int64 1318613 messages
metric rabbitmq_fd_used int64 162 fd
metric rabbitmq_mem_used int64 131505584 bytes
metric rabbitmq_fd_total int64 4096 fd
metric rabbitmq_disk_free_alarm_status uint32 1
metric rabbitmq_proc_used int64 2621 processes
metric rabbitmq_mem_limit int64 40494145536 bytes
metric rabbitmq_mem_alarm_status uint32 1
metric rabbitmq_sockets_used int64 141 fd
metric rabbitmq_messages_unacknowledged int64 0 messages
metric rabbitmq_messages_ready int64 6780 messages
metric rabbitmq_proc_total int64 1048576 processes
```
rabbitmq_status.py from this repo needs to be modified to support this required metric.

Cheers! :)

**Comment by nrb** [comment]
Looks like we'll need to grab https://github.com/rcbops/rpc-openstack/commit/42bd085e798548239c48b769709f2c24ada64b0a and https://github.com/rcbops/rpc-openstack/commit/c3950819cda7951429414e897d734d6759276af1 to account for this.

@xeregin what version are you testing currently? 10.1.10?

**Comment by nrb** [comment]
This was also reported on https://bugs.launchpad.net/openstack-ansible/+bug/1466171, so it's existed for a couple versions.

**Comment by nrb** [comment]
Double checked - this was a result of mistakes in tagging. The change is merged (https://github.com/rcbops/rpc-maas/pull/209), and will go into 10.1.10.

@BjoernT @b3rnard0

**Comment by xeregin** [comment]
I was testing 10.1.9. Missed that bug in launchpad.
