### ISSUE TITLE
Alert on predictive failure

### ISSUE THREAD

**Issue by kstev** [rcbops/rpc-maas#215]
Dell script openmanage.py does not seem to be catching predictive drive failures. Unfortunately predictive failures do not "degrade" virtual disks or show up under omreport chassis. The failure predicted status may be found with an "omreport storage pdisk controller=0" under the "Failure Predicted" reading.

**Comment by git-harry** [comment]
This repo is no longer actively maintained. If this issue is still valid please open a new issue at https://github.com/rcbops/rpc-openstack/issues
