### ISSUE TITLE
Need to monitor mysql connection count versus configured max

### ISSUE THREAD

**Issue by mancdaz** [rcbops/rpc-maas#222]
As a result of some recent occurrences, it was deemed a good idea to be able to monitor mysql connection count versus the configured max, so that we can alert when the node is approaching the configured maximum.

**Comment by mancdaz** [comment]
The PR for kilo (in rpc-openstack) is here:

https://github.com/rcbops/rpc-openstack/pull/552

Once that merges we can backport the plugin changes.

**Comment by git-harry** [comment]
This repo is no longer actively maintained. If this issue is still valid please open a new issue at https://github.com/rcbops/rpc-openstack/issues
