### ISSUE TITLE
Set Status to Critical if no data is returned on hardware checks

### ISSUE THREAD

**Issue by mtsprout** [rcbops/rpc-maas#229]
For checks that use manufacturer's tools (i.e. OpenManage or hp*cli) to return status of hardware, a check that returns no data should default to a critical status as it is most likely an issue that requires further investigation.

**Comment by b3rnard0** [comment]
@git-harry @d34dh0r53 Can we triage this bug?

**Comment by sigmavirus24** [comment]
cc @andymcc

**Comment by git-harry** [comment]
Issue moved to https://github.com/rcbops/rpc-openstack/issues/1093
