### ISSUE TITLE
Separate Ceph monitoring into its own role

### ISSUE THREAD

**Issue by Alfano93** [rcbops/rpc-maas#252]
## Is this a feature or a bug?

- [x] Feature _(request for enhancement, new functionality)_
- [ ] Bug _(something is broken)_

## Which version of rpc-openstack does this issue relate to?
- newton-14.0

Run `git log --pretty=oneline | head -n 1` and provide the output below between
the backtick lines:

```
r14.0.0
```

## What happened?

Ceph is now deployed as its own environment and is no longer included in the Openstack inventory files. Therefore, monitoring cannot be deployed from site.yml (setup-maas.yml) since Ansible has no knowledge of the Ceph nodes. 

There should be a way to deploy monitoring from the Ceph deployment host and only drop the monitors related to Ceph. Separating the Openstack monitors and Ceph monitors into their own roles would give deployments more flexibility and keep the two environments separate (Openstack doesn't know about Ceph, Ceph doesn't know about Openstack). It should work in both 14.04 and 16.04.  

## Do you think the documentation team wants to know about this?

- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [ ] No documentation required for this change

## Does your change require a release note?

- [ ] Yes, it's a pretty big deal like I am and I've made a reno note!
- [ ] Nope, this change has no major impact.

**Comment by Alfano93** [comment]
This is a list of changes that I had to make when I first deployed MaaS on ceph nodes. I now make these changes through the inventory, but it could give some direction as to which tasks could be taken out for Ceph nodes.

Had to comment out Drop pip config in /etc/ansible/roles/pip_install/tasks/configure.yml

Had to comment out keystone in /etc/ansible/roles/rpc_maas/tasks/main.yml

Had to comment out swift

Had to add /etc/ansible/roles/rpc_maas/library/ceph_osd_host_facts

Had to change line 586 in /etc/ansible/roles/rpc_maas/defaults/main.yml

    maas_venv: "/openstack/venvs/maas-ceph"


Had to comment out name: Create openrc file in /etc/ansible/roles/rpc_maas/tasks/agent_install_local.yml

Had to comment out name: Install pip packages for containers to venv in /etc/ansible/roles/rpc_maas/tasks/package_install.yml

Removed the rabbitMQ playbook (because there is no rabbit)

Removed create_my_cnf.yml because there is no Galera

Every mention of 

    delegate_to: {{ physical_host }} 

was changed to {{ ansible_hostname }}

In /etc/ansible/roles/rpc_maas/tasks/process.yml removed the filebeat checks

Commented out ensure_cinder_volume_checks because there is no cinder

Removed the cinder checks from main.yml as well

**Comment by cloudnull** [comment]
I agree with this issue, however, I've written a general purpose spec to try and tackle this for all of the monitors. See https://github.com/rcbops/rpc-maas/issues/255 I think we should close this issue and focus on this as a general improvement in our monitoring capabilities.

**Comment by Alfano93** [comment]
I agree. I'm all for closing this.
