### ISSUE TITLE
RFC - RPC-MaaS role breakdown

### ISSUE THREAD

**Issue by cloudnull** [rcbops/rpc-maas#255]
### RFC - RPC-MaaS role breakdown
**2017-05-25 10:00**
**maas, rpc, playbooks, roles**

The RPC-MaaS role is too specific, hard to understand, slow to execute, and is nearly impossible to run standalone. The role makes far too many assumptions that an entire OpenStack cloud following the standard RPC reference architecture and in many cases folks may want to deploy RPC-MaaS outside of the typical reference architecture. Additionally, deployers may want to "pick and choosing" various checks based on their specific needs.

I am proposing that we abolish the RPC-MaaS role and turn it's tasks, templates, and files into a set of standalone playbooks which can be used to target specific hosts, checks, and use-cases. 

#### Problem description

* The RPC-MaaS role uses ansible delegation to target specific node types which span all groups within an OpenStack cloud. Sadly this approach creates a situation where we see far too many skipped tasks causing extended maintenance windows and prolongs deployment times. The use of task delegation also means any consumer of this role will need to have a full OpenStack inventory built out even when deploying services outside of a typical OpenStack cloud following both the [TC managed tags for architecture](https://governance.openstack.org/tc/reference/tags/tc_approved-release.html).

* Deployment times of this role are exaggerated due to how Ansible skips tasks when conditionals are not met. the role, in its current form, could take many hours to execute depending on the size of the OpenStack cluster. For example, it common for us to see this role take around 45 minutes to execute on an AIO.

* Trying to use standalone monitors is nearly impossible without having a fundamental understanding of how the role works. While this has been recently improved it's been determined that the current design pattern could not be optimized in such a way to allow a deployer to decouple components from one another without always constructing a full cloud inventory even if components were not used.

#### Proposed change

I propose we decommission the role entirely and pivot to a set of standalone playbooks. This will give operators the ability to choose which monitors they want to deploy. We will still keep the ability to simply deploy all of the monitors however that will be something executed from a "meta" playbook. The underlying intention is to allow our monitoring solution to span multiple releases without requiring an OpenStack upgrade to update our monitors. Deployers should have the ability to benefit from monitoring improvements on all supported releases of our products without facing self-imposed caps. While there will be times when a system upgrade is required to receive the full benefit of an updated solution, these types of limitations should be technical in nature and not something we arbitrarily set.  

###### Alternatives

We could continue down our current path and try and further improve execute leaving all checks and tasks bundled. 

###### Playbook/Role impact

* There will a set of playbooks created to facilitate installing monitors.
* The RPC-MaaS role will be removed.
* The RPC-O repository will have its RPC-MaaS installation playbook modified to point at the new set of playbooks.

###### Upgrade impact

* There will be no negative upgrade impact. The files installed, checks dropped, and monitors run will be the same. 

* There will be a positive upgrade impact because the execution of monitoring will be faster and more flexible. 

###### Security impact

N/A

###### Performance impact

Converting RPC-MaaS to a set of standalone playbooks will enable far better performance.

###### End user impact

N/A

###### Deployer impact

* The time to execution will be faster which means that the deployer will take less time to run the deployment.

* Deployers will have a better understanding of how things are put together.

* Deployers will be able to create the standalone inventory to support decoupled deployments of standalone services (IE: Ceph, Cinder, Swift).

###### Developer impact

* The role work would cease to exist.

* All of the playbooks would be able to be tested individually which will enable faster turnaround for testing/gating.

###### Dependencies

N/A

###### Assignee(s)

Primary Assignee:
  Kevin.Carter@Rackspace.com (cloudnull)

###### Work items

* Create a new repository for the standalone playbooks.

* Begin porting the tasks from the role to standalone playbooks. Each playbook should have a functional test alone with it.

* Document the playbooks and the required inventory for each playbook to be executed.

#### Testing

* Each playbook will be tested standalone, each playbook will need to have an integration test.

* A set of lint checks will be run on all playbooks, files, and templates.

* A documentation test will be run.

#### Documentation impact

New documentation will be created so developers and deployers know how the playbooks work and how they can leverage them for their specific deployments.

#### References

N/A

**Comment by Alfano93** [comment]
+1 This captures 252 as part of its scope. The individual playbooks would give deployments more flexibility in setting up MaaS.

**Comment by antonym** [comment]
+1, definitely would be nice to break it all out so that it works with more deployments and so that it doesn't spin so long on missed tasks. LGTM.

**Comment by mrhillsman** [comment]
This looks great, allows for better understanding of what is happening, increases flexibility of use by being modular, removes a lot of unnecessary overhead +1000

**Comment by supermari0** [comment]
+1 especially for the standalone tests. As someone new to these playbooks, separate tests for each playbook would help me understand the desired end state of each component.

**Comment by galstrom21** [comment]
"The RPC-O repository will have its RPC-MaaS installation playbook modified to point at the new set of playbooks."

Can we make sure that part of the design principle with this split out is that RPC-O is not tied to these new repos in a monolithic way (like the current relationship between RPCO and OSA). The overarching goal (did not see this in the spec) would be for monitoring to be able to be updated, and that update could be applied across multiple versions of deployed openstack environments.

**Comment by galstrom21** [comment]
Also, for more justification, we need to accept that there are at least 3 offerings this set of playbooks needs to support. A full openstack compute deployment, a standalone ceph deployment, and a standalone swift deployment (where standalone means 'does not include compute control plane'.

**Comment by cloudnull** [comment]
@galstrom21 
To the first point, yes. The primary goal here is to ensure that we're developing this as a stand-alone project and that it can be consumed independently from the main rpc-o release train and to improve understanding and readability of the monitoring components. (I will update the spec to cover this).

To the second point, absolutely. While this is the intent of the split-out (improving flexibility) the initial work would be to ensure complete compatibility with the existing stack and then begin decoupling in a future iteration (I will add this to the highlevel statement of work)

**Comment by galstrom21** [comment]
👍

**Comment by cloudnull** [comment]
The refactoring work for this RFC has been completed. Please review [ #256 ]. This initial PR converts the role into playbooks, modifies the documentation to support the new structure, and updates the tests (though they are not broken out yet). At this point, the work is ready for folks to take it for a spin. Please submit all new feedback on the implementation of this RFC within the PR #256.

**Comment by cloudnull** [comment]
This was implemented and merged here  [ #256 ]
