### ISSUE TITLE
stable/kilo: Update container_storage_checks.yaml.j2

### ISSUE THREAD

**Issue by npawelek** [rcbops/rpc-maas#264]
The stable/kilo branch has a bug in the container_storage_checks template which deploys with a venv. As venv's don't yet exist in Kilo, it causes the check to fail.

https://github.com/rcbops/rpc-maas/blob/stable/kilo/templates/container_storage_checks.yaml.j2#L9-L10

Submitting a PR to update the template to use the plugin directly.

**Comment by BjoernT** [comment]
That was addressed with https://github.com/rcbops/rpc-maas/commit/236a4082ad95e98ef94800b7ad3f0a0fef74612b did you use an older code base ?
