### ISSUE TITLE
Install OEM tools for hardware monitoring

### ISSUE THREAD

**Issue by cfarquhar** [rcbops/rpc-maas#268]
The Dell- and HP-specific plugins assume the vendor specific tools (i.e. Dell OMSA or HP MCP) are installed.  Some brief digging suggests this is being performed manually during deployment time \[1].  

Ideally, the rpc-maas playbooks would handle this.

\[1] https://github.com/rsoprivatecloud/rpc-deployments/tree/master/pre-qc#hp-management-component-pack-(mcp)

**Comment by BjoernT** [comment]
Yes I had the same problem and added the HP tools via https://github.com/rsoprivatecloud/openstack-ops/commit/db84abb14d9fbac7098f68d45a0bec78d08323e6 inside the ops module. The independence of the roles seem to make it a copy and past job now, unless we move the HP and Dell monitoring into it's own role

**Comment by cloudnull** [comment]
we can now isolate this using the following playbook https://github.com/rcbops/rpc-maas/blob/master/playbooks/maas-host-vendor.yml

which can install hp or dell specific tools here:
* https://github.com/rcbops/rpc-maas/blob/master/playbooks/common-tasks/maas-host-vendor-dell.yml
* https://github.com/rcbops/rpc-maas/blob/master/playbooks/common-tasks/maas-host-vendor-hp.yml

**Comment by cloudnull** [comment]
@cfarquhar @BjoernT if you have a list of repos and packages to install i'd be happy to add them

**Comment by BjoernT** [comment]
For HP see my previous comment but we mainly install  hpasmcli, hpssacli, hponcfg.
Dell I have to dig out myself

**Comment by cfarquhar** [comment]
@cloudnull Thanks!  Here is a copy/paste from the deployment team's repo:

### Dell 
```
# Install OMSA
SOURCES_FILE="/etc/apt/sources.list.d/linux.dell.com.sources.list"
CODENAME=$(lsb_release -c | awk '{print $NF}')
 
if [[ -f ${SOURCES_FILE} ]] && [[ $(grep "linux.dell.com" ${SOURCES_FILE}) ]]; then
    echo -e "INFORM\tDell OMSA repository already installed"
else
    echo "deb http://linux.dell.com/repo/community/ubuntu ${CODENAME} openmanage/740" \
        >> "${SOURCES_FILE}" && echo -e "PASS\tInstalled Dell OMSA repository"
fi
 
# Verify the OMSA repository keys
(gpg --keyserver pool.sks-keyservers.net --recv-key 1285491434D8786F \
    &>/dev/null && echo -e "PASS\tDownloading GPG key") \
    || echo -e "FAIL\tDownloading GPG key"
 
(gpg -a --export 1285491434D8786F | apt-key add - &>/dev/null \
    && echo -e "PASS\tInstalling GPG key") \
    || echo -e "FAIL\tInstalling GPG key"
 
apt-get -qq update
(apt-get -qq install srvadmin-all &>/dev/null \
    && echo -e "PASS\tInstalling OMSA packages") \
    || echo -e "FAIL\tInstalling OMSA packages"
 
(/opt/dell/srvadmin/sbin/srvadmin-services.sh restart &>/dev/null \
    && sleep 30 \
    && echo -e "PASS\tStarting OMSA services") \
    || echo -e "FAIL\tStarting OMSA services"
 
if [[ $(lsb_release -r | awk '{print $NF}') == 14.04 ]]; then
    # Enable persistence
    for OMSA_SERVICE in dataeng instsvcdrv dsm_om_connsvc racsvc.sh
    do
        (update-rc.d ${OMSA_SERVICE} defaults &>/dev/null \
            && echo -e "PASS\tEnable ${OMSA_SERVICE} persistence") \
            || echo -e "FAIL\tEnable ${OMSA_SERVICE} persistence"
    done
fi
```

### HP
```
# Add HP MCP repository
SOURCES_FILE="/etc/apt/sources.list.d/linux.hp.com.sources.list"
CODENAME=$(lsb_release -c | awk '{print $NF}')
 
if [[ -f ${SOURCES_FILE} ]] && [[ $(grep "linux.hp.com" ${SOURCES_FILE}) ]]; then
    echo -e "INFORM\tHP MCP repository already installed"
else
    if [[ ${CODENAME} == trusty ]]; then
        echo "deb http://downloads.linux.hp.com/SDR/repo/mcp/ubuntu ${CODENAME}/9.50 non-free" \
            >> "${SOURCES_FILE}" && echo -e "PASS\tInstalled HP MCP repository"
    elif [[ ${CODENAME} == precise ]]; then
        echo "deb http://downloads.linux.hp.com/SDR/repo/mcp/ubuntu ${CODENAME}/9.40 non-free" \
            >> "${SOURCES_FILE}" && echo -e "PASS\tInstalled HP MCP repository"
    fi
fi
 
# Download and verify the HP MCP repository keys
for FINGERPRINT in 5CE2D476 B1275EA3
do  
    (gpg --keyserver pool.sks-keyservers.net --recv-key ${FINGERPRINT} \
        &>/dev/null && echo -e "PASS\tDownloading GPG key [${FINGERPRINT}]") \
        || echo -e "FAIL\tDownloading GPG key [${FINGERPRINT}]"
 
    (gpg -a --export ${FINGERPRINT} | apt-key add - &>/dev/null \
        && echo -e "PASS\tInstalling GPG key [${FINGERPRINT}]") \
        || echo -e "FAIL\tInstalling GPG key [${FINGERPRINT}]"
done
 
# Install packages
MCPPKGS="hp-health hponcfg hpssacli hpsmh hp-snmp-agents"
apt-get -qq update
(apt-get -y install ${MCPPKGS} \
    && echo -e "PASS\tInstalling HP MCP packages") \
    || echo -e "FAIL\tInstalling HP MCP packages"
 
(/etc/init.d/hp-health restart \
    && sleep 30 \
    && echo -e "PASS\tStarting hp-health services") \
    || echo -e "FAIL\tStarting hp-health services"
```

**Comment by antonym** [comment]
Have some of this replicated to a degree in Ansible if it's helpful:

https://github.com/antonym/ecopoiesis-utility-builder-centos/blob/master/roles/prep-dell/tasks/main.yml

https://github.com/antonym/ecopoiesis-utility-builder-centos/blob/master/roles/prep-hp/tasks/main.yml

You could probably drop off the hpsum/dsu stuff as I was testing a bootable centos image for handling all firmware/bios updates during provisioning.

**Comment by odyssey4me** [comment]
Just a note that the role itself should not add these repositories - perhaps the tests can, but the role itself should expect that the repositories are already there. If the role adds the repositories then we'll have to ensure that the config to override this is included in the artifacts repo config and that any extra repositories are included in the apt artifacting.
