### ISSUE TITLE
Support for excluded checks/alarms in verification playbook

### ISSUE THREAD

**Issue by cfarquhar** [rcbops/rpc-maas#279]
The `maas-verify.yml` playbook doesn't appear to honor `maas_excluded_checks` or `maas_excluded_alarms` variables \[1].  I would have expected to see the `--excludedchecks` argument passed to `rpc-maas-tool.py` \[2].

Please note that I haven't actually tested this, so I could be missing something.  I happened to notice this while investigating an issue in rpc-openstack prior to rpc-maas being moved to a standalone repo.

\[1] https://github.com/rcbops/rpc-maas/blob/c967c5e/playbooks/maas-verify.yml#L49-L55
\[2] https://github.com/rcbops/rpc-maas/blob/c967c5e/playbooks/files/tools/rpc-maas-tool.py#L289-L293

**Comment by cloudnull** [comment]
@cfarquhar the current check method simply verifies the enabled checks. If a check has been set in the ``maas_excluded_checks`` variable the check should never be deployed, or if the check is deployed it should be disabled which the tool would omit from verification automatically. If this is not working as expected please let me know and I will make adjustments.

**Comment by cloudnull** [comment]
I believe this has been corrected in the current master. please let me know if you encounter any further issues with this.
