### ISSUE TITLE
Add support for HTTP proxy with rackspace-monitoring-agent

### ISSUE THREAD

**Issue by cfarquhar** [rcbops/rpc-maas#308]
The Rackspace monitoring agent supports a `monitoring_proxy_url` configuration item in `/etc/rackspace-monitoring-agent.cfg`.  The template for this file should expose the variable.

In openstack-ansible, the equivalent variable name is `proxy_env_url`, so I'll use that as a starting point.

**Comment by npawelek** [comment]
@cfarquhar Just an FYI, if environment variables are properly configured for `http_proxy`, the agent automatically picks up the settings without having to define it in the agent configuration.

**Comment by cfarquhar** [comment]
Thanks @npawelek.  

I have the proxy configured using OSA's standard `proxy_env_url` method, which results in `http{,s}_proxy` (and the uppercase variants) being added to `/etc/environment`.  

The agent doesn't seem to account for any environment variables in the init configs \[2] \[3].  There are several places we could fix this, but I'm not sure which is "best." 

How are you exposing the environment variables to the agent?  Perhaps I'm overlooking something simple.

\[1] https://github.com/openstack/openstack-ansible/blob/39900e1bcc2dc2580e64d6be15388e2f3c0890eb/etc/openstack_deploy/user_variables.yml#L122-L130

\[2] https://github.com/virgo-agent-toolkit/rackspace-monitoring-agent/blob/master/cmake/package/systemd/service.in

\[3] https://github.com/virgo-agent-toolkit/rackspace-monitoring-agent/blob/master/cmake/package/debian/service.upstart.in
