### ISSUE TITLE
breaking changes in netaddr

### ISSUE THREAD

**Issue by jklint** [rcbops/rpc-maas#752]
https://github.com/rcbops/rpc-maas/blob/fb279008cdc80b714ad74781b438277dc57a71f0/playbooks/vars/maas.yml#L358

https://github.com/ansible-collections/ansible.utils/issues/331

We should pin netaddr to <1.0 or ==0.10.1

Specifically it breaks on:

TASK [Determine endpoint components] ********************************************************************************************************************************************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'IPAddress' object has no attribute 'is_private'
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"<stdin>\", line 102, in <module>\n  File \"<stdin>\", line 94, in _ansiballz_main\n  File \"<stdin>\", line 40, in invoke_module\n  File \"/usr/lib/python3.8/runpy.py\", line 207, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.8/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_service_discovery_payload_3lkopzss/ansible_service_discovery_payload.zip/ansible/modules/service_discovery.py\", line 459, in <module>\n  File \"/tmp/ansible_service_discovery_payload_3lkopzss/ansible_service_discovery_payload.zip/ansible/modules/service_discovery.py\", line 439, in main\n  File \"/tmp/ansible_service_discovery_payload_3lkopzss/ansible_service_discovery_payload.zip/ansible/modules/service_discovery.py\", line 181, in generate_facts\n  File \"/tmp/ansible_service_discovery_payload_3lkopzss/ansible_service_discovery_payload.zip/ansible/modules/service_discovery.py\", line 247, in validate_endpoints\n  File \"/tmp/ansible_service_discovery_payload_3lkopzss/ansible_service_discovery_payload.zip/ansible/modules/service_discovery.py\", line 335, in validate_private_ip\nAttributeError: 'IPAddress' object has no attribute 'is_private'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

**Comment by BjoernT** [comment]
This has been fixed
